### PR TITLE
Add Swedish translation (sv)

### PR DESCRIPTION
**Pull request by indiehjaerta**
Issue #76 adds Swedish Translation files

### CODE REVIEW

**Comment by AndrGab** [comment]
Thanks @indiehjaerta 
Can you adjust i18n.js file please?

**Review by AndrGab — CHANGES_REQUESTED** [review]
i18n.js file adjustment needed

**Comment by indiehjaerta** [comment]
> Thanks @indiehjaerta Can you adjust i18n.js file please?

Yes of course, hope this is correct.

**Comment by AndrGab** [comment]
Perfect!
Thank you for your time and collaboration 😃

**Review by AndrGab — APPROVED** [review]

**Pull request merged**
