### PR TITLE
zod-library-added

### LINKED ISSUE #163: 🚀 Feature: Add Zod Library
### 🔖 Feature description

Using Zod, a popular schema declaration and validation library, developers can enforce proper email & password format and consistency between email fields & password fields easily.

### 🎤 Why is this feature needed ?

Validating user input is crucial in any web application to maintain data integrity and provide a good user experience. Email validation is particularly important as it directly impacts user notifications, password resets, and communication channels. Password validation is also an important factor to let user set the strong password for his/her account in our website.

### ✌️ How do you aim to achieve this?

I would like to achieve this by adding Zod Library to our Web App. By using email and password validations in zod library. Please assign to me this issue under hacktoberfest to proceed. Thank You!

### 🔄️ Additional Information

_No response_

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/andrgab/medirepoweb/blob/main/CONTRIBUTING.md)

### 🏢 Have you read the Code of conduct

- [X] I have read the [Code of conduct](https://github.com/andrgab/medirepoweb/blob/main/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Aneeshaik**
Hey @AndrGab! I have added email and password validation. Please review it and Merge my PR, closes #163  . Thank you!

### CODE REVIEW

**Comment by AndrGab** [comment]
we need to upgrade nodeJs

**Comment by Aneeshaik** [comment]
> we need to upgrade nodeJs

will look into that

**Comment by Aneeshaik** [comment]
Hey @AndrGab! As the backend is not in nodejs I can't be able to update it. Please do it from your end and merge my PR. Thank you!

**Comment by Aneeshaik** [comment]
Hey @AndrGab! Can you please share me the nodejs file. So that I can look into it

**Pull request closed without merging**
